---
title: "HistopathPCaLLM statement sanity check"
author: "T. D. Laajala"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Process data

## Libraries

```{r libs}
library(dplyr)
```

## Read in tsv

```{r read_tsv}
sanity <- read.table("sanity.tsv", sep="\t", header=TRUE, quote="ยง", comment.char="^")
# Sanitize some extra output
for(col in 1:ncol(sanity)){
  sanity[,col] <- gsub(": |<|>", "", sanity[,col])
}

# Inspect
head(sanity)
tail(sanity)

colnames(sanity)[grep("hit", colnames(sanity))] <- c("hitSampleType", "hitSampleTypeComment", "hitMalignancy", "hitMalignancyComment", "hitGleason", "hitGleasonComment", "hitGrammar", "hitGrammarComment")

# Subset according to model
sanity_k2 <- sanity %>% filter(model == "moonshotai/kimi-k2-instruct")
sanity_o1 <- sanity %>% filter(model == "openai/o1")

# Subset according to language
sanity_eng_k2 <- sanity_k2 %>% filter(lang == 0)
sanity_eng_o1 <- sanity_o1 %>% filter(lang == 0)
sanity_fin_k2 <- sanity_k2 %>% filter(lang == 1)
sanity_fin_o1 <- sanity_o1 %>% filter(lang == 1)
sanity_swe_k2 <- sanity_k2 %>% filter(lang == 2)
sanity_swe_o1 <- sanity_o1 %>% filter(lang == 2)

# Run parameters
indices <- 0:99
```

# English

```{r, results='asis', echo=FALSE}

for(i in indices){
	
	cat(paste0("## Statement index ", i, "\n\n"))
	
	dat_k2_cens0 <- sanity_eng_k2 %>% filter(inputIndex == i & cens == 0)
	dat_o1_cens0 <- sanity_eng_o1 %>% filter(inputIndex == i & cens == 0)
	dat_k2_cens1 <- sanity_eng_k2 %>% filter(inputIndex == i & cens == 1)
	dat_o1_cens1 <- sanity_eng_o1 %>% filter(inputIndex == i & cens == 1)

	cat("\n\n### Signal containing\n")

	cat("\n\nOpenAI o1\n\n")
	cat(knitr::kable(dat_o1_cens0[,grep("hit", colnames(dat_o1_cens0))], format = "html"))
		
	cat("\n\nKimi K2\n\n")
	cat(knitr::kable(dat_k2_cens0[,grep("hit", colnames(dat_k2_cens0))], format = "html"))
	
	cat("\n\n### Censored statements\n")

	cat("\n\nOpenAI o1\n\n")
	cat(knitr::kable(dat_o1_cens1[,grep("hit", colnames(dat_o1_cens1))], format = "html"))
		
	cat("\n\nKimi K2\n\n")
	cat(knitr::kable(dat_k2_cens1[,grep("hit", colnames(dat_k2_cens1))], format = "html"))
	
}
```


# Finnish

```{r, results='asis', echo=FALSE}

for(i in indices){
	
	cat(paste0("## Statement index ", i, "\n\n"))
	
	dat_k2_cens0 <- sanity_fin_k2 %>% filter(inputIndex == i & cens == 0)
	dat_o1_cens0 <- sanity_fin_o1 %>% filter(inputIndex == i & cens == 0)
	dat_k2_cens1 <- sanity_fin_k2 %>% filter(inputIndex == i & cens == 1)
	dat_o1_cens1 <- sanity_fin_o1 %>% filter(inputIndex == i & cens == 1)

	cat("\n\n### Signal containing\n")

	cat("\n\nOpenAI o1\n\n")
	cat(knitr::kable(dat_o1_cens0[,grep("hit", colnames(dat_o1_cens0))], format = "html"))
		
	cat("\n\nKimi K2\n\n")
	cat(knitr::kable(dat_k2_cens0[,grep("hit", colnames(dat_k2_cens0))], format = "html"))
	
	cat("\n\n### Censored statements\n")

	cat("\n\nOpenAI o1\n\n")
	cat(knitr::kable(dat_o1_cens1[,grep("hit", colnames(dat_o1_cens1))], format = "html"))
		
	cat("\n\nKimi K2\n\n")
	cat(knitr::kable(dat_k2_cens1[,grep("hit", colnames(dat_k2_cens1))], format = "html"))
	
}
```

# Swedish

```{r, results='asis', echo=FALSE}

for(i in indices){
	
	cat(paste0("## Statement index ", i, "\n\n"))
	
	dat_k2_cens0 <- sanity_swe_k2 %>% filter(inputIndex == i & cens == 0)
	dat_o1_cens0 <- sanity_swe_o1 %>% filter(inputIndex == i & cens == 0)
	dat_k2_cens1 <- sanity_swe_k2 %>% filter(inputIndex == i & cens == 1)
	dat_o1_cens1 <- sanity_swe_o1 %>% filter(inputIndex == i & cens == 1)

	cat("\n\n### Signal containing\n")

	cat("\n\nOpenAI o1\n\n")
	cat(knitr::kable(dat_o1_cens0[,grep("hit", colnames(dat_o1_cens0))], format = "html"))
		
	cat("\n\nKimi K2\n\n")
	cat(knitr::kable(dat_k2_cens0[,grep("hit", colnames(dat_k2_cens0))], format = "html"))
	
	cat("\n\n### Censored statements\n")

	cat("\n\nOpenAI o1\n\n")
	cat(knitr::kable(dat_o1_cens1[,grep("hit", colnames(dat_o1_cens1))], format = "html"))
		
	cat("\n\nKimi K2\n\n")
	cat(knitr::kable(dat_k2_cens1[,grep("hit", colnames(dat_k2_cens1))], format = "html"))
	
}
```


# Session info

```{r session}
sessionInfo()
```

